### ISSUE TITLE
Svg example crash for thread num > 0

### ISSUE THREAD

**Issue by mgrudzinska** [thorvg/thorvg#1389]
```
    #0 0x101647e11 in wrap_setlocale+0x181 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x30e11)
    #1 0x100b9fdd6 in svgPathToTvgPath(char const*, tvg::Array<tvg::PathCommand>&, tvg::Array<tvg::Point>&) tvgSvgPath.cpp:560
    #2 0x100ba73d0 in _appendShape(SvgNode*, tvg::Shape*, Box const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) tvgSvgSceneBuilder.cpp:398
    #3 0x100ba29a5 in _sceneBuildHelper(SvgNode const*, Box const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, int, bool*) tvgSvgSceneBuilder.cpp:741
    #4 0x100ba2708 in _sceneBuildHelper(SvgNode const*, Box const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, int, bool*) tvgSvgSceneBuilder.cpp:733
    #5 0x100ba0a0b in svgSceneBuild(SvgNode*, float&, float&, float&, float&, float&, float&, AspectRatioAlign, AspectRatioMeetOrSlice, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, SvgViewFlag) tvgSvgSceneBuilder.cpp:796
    #6 0x100b881d4 in SvgLoader::run(unsigned int) tvgSvgLoader.cpp:3491
    #7 0x100b4a72d in tvg::Task::operator()(unsigned int) tvgTaskScheduler.h:81
    #8 0x100b49fa8 in tvg::TaskSchedulerImpl::run(unsigned int) tvgTaskScheduler.cpp:138
    #9 0x100b49c21 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::'lambda'()> >(void*) thread:298
    #10 0x7ff8171c7258 in _pthread_start+0x7c (libsystem_pthread.dylib:x86_64+0x6258)
    #11 0x7ff8171c2c7a in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x1c7a)
```

tested on mac, ocures +- every 10-20 calls of the example

**Comment by mgrudzinska** [comment]
solved by #1390
