### ISSUE TITLE
Use of unitialized values

### ISSUE THREAD

**Issue by qarmin** [thorvg/thorvg#1410]
Compilation flags
```
CC=clang CXX=clang++  meson  -Dtools=svg2png -Db_sanitize=memory -Db_lundef=false -Dcpp_args="-fsanitize-recover=memory" . build
```
Command `svg2png AA_5.svg  -r 400x400` on file from #1409

```
==585790==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f14fc5ec02d in tvg::Picture::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /home/rafal/test/thorvg/build/../src/lib/tvgPicture.cpp:56:9
    #1 0x563fd226cde5 in Renderer::render(char const*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned int) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:84:39
    #2 0x563fd226c415 in App::renderFile(char const*) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:342:25
    #3 0x563fd226b6ee in App::setup(int, char**) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:264:36
    #4 0x563fd226ae35 in main /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:413:16
    #5 0x7f14fbe23a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #6 0x7f14fbe23b48 in __libc_start_main csu/../csu/libc-start.c:360:3
    #7 0x563fd21e2554 in _start (/home/rafal/test/thorvg/build/src/bin/svg2png/svg2png+0x24554) (BuildId: 4232bf1566260aa8e8df3c044a913cc0946ea6d8)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/rafal/test/thorvg/build/../src/lib/tvgPicture.cpp:56:9 in tvg::Picture::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&)
Uninitialized bytes in __interceptor_fopen64 at offset 44 inside [0x703000000030, 45)
==585790==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f14fc2dab13 in std::__basic_file<char>::open(char const*, std::_Ios_Openmode, int) /build/gcc-13-oz92yP/gcc-13-13-20230320/build/x86_64-linux-gnu/libstdc++-v3/src/c++98/basic_file.cc:254:25
    #1 0x7f14fc32440d in std::basic_filebuf<char, std::char_traits<char>>::open(char const*, std::_Ios_Openmode) /build/gcc-13-oz92yP/gcc-13-13-20230320/build/x86_64-linux-gnu/libstdc++-v3/include/bits/fstream.tcc:184:16
    #2 0x7f14fc3244e6 in std::basic_filebuf<char, std::char_traits<char>>::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::_Ios_Openmode) /build/gcc-13-oz92yP/gcc-13-13-20230320/build/x86_64-linux-gnu/libstdc++-v3/include/fstream:339:20
    #3 0x7f14fc3244e6 in std::basic_ifstream<char, std::char_traits<char>>::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::_Ios_Openmode) /build/gcc-13-oz92yP/gcc-13-13-20230320/build/x86_64-linux-gnu/libstdc++-v3/include/fstream:706:22
    #4 0x7f14fc66b4cb in SvgLoader::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /home/rafal/test/thorvg/build/../src/loaders/svg/tvgSvgLoader.cpp:3570:7
    #5 0x7f14fc5e3638 in LoaderMgr::loader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, bool*) /home/rafal/test/thorvg/build/../src/lib/tvgLoader.cpp:174:21
    #6 0x7f14fc5ed1ed in tvg::Picture::Impl::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /home/rafal/test/thorvg/build/../src/lib/tvgPictureImpl.h:220:18
    #7 0x7f14fc5ebfec in tvg::Picture::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /home/rafal/test/thorvg/build/../src/lib/tvgPicture.cpp:58:19
    #8 0x563fd226cde5 in Renderer::render(char const*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned int) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:84:39
    #9 0x563fd226c415 in App::renderFile(char const*) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:342:25
    #10 0x563fd226b6ee in App::setup(int, char**) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:264:36
    #11 0x563fd226ae35 in main /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:413:16
    #12 0x7f14fbe23a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #13 0x7f14fbe23b48 in __libc_start_main csu/../csu/libc-start.c:360:3
    #14 0x563fd21e2554 in _start (/home/rafal/test/thorvg/build/src/bin/svg2png/svg2png+0x24554) (BuildId: 4232bf1566260aa8e8df3c044a913cc0946ea6d8)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /build/gcc-13-oz92yP/gcc-13-13-20230320/build/x86_64-linux-gnu/libstdc++-v3/src/c++98/basic_file.cc:254:25 in std::__basic_file<char>::open(char const*, std::_Ios_Openmode, int)
Uninitialized bytes in __interceptor_fopen64 at offset 44 inside [0x706000000000, 45)
==585790==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x563fd226f4ed in lodepng_save_file(unsigned char const*, unsigned long, char const*) /home/rafal/test/thorvg/build/../src/bin/svg2png/lodepng.cpp:391:10
    #1 0x563fd22a17af in lodepng::save_file(std::vector<unsigned char, std::allocator<unsigned char>> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /home/rafal/test/thorvg/build/../src/bin/svg2png/lodepng.cpp:6231:10
    #2 0x563fd22a35da in lodepng::encode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned char const*, unsigned int, unsigned int, LodePNGColorType, unsigned int) /home/rafal/test/thorvg/build/../src/bin/svg2png/lodepng.cpp:6396:22
    #3 0x563fd22a37a8 in lodepng::encode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::vector<unsigned char, std::allocator<unsigned char>> const&, unsigned int, unsigned int, LodePNGColorType, unsigned int) /home/rafal/test/thorvg/build/../src/bin/svg2png/lodepng.cpp:6404:10
    #4 0x563fd226e06b in PngBuilder::build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned int, unsigned int, unsigned int*) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:63:26
    #5 0x563fd226d584 in Renderer::render(char const*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned int) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:150:17
    #6 0x563fd226c415 in App::renderFile(char const*) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:342:25
    #7 0x563fd226b6ee in App::setup(int, char**) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:264:36
    #8 0x563fd226ae35 in main /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:413:16
    #9 0x7f14fbe23a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #10 0x7f14fbe23b48 in __libc_start_main csu/../csu/libc-start.c:360:3
    #11 0x563fd21e2554 in _start (/home/rafal/test/thorvg/build/src/bin/svg2png/svg2png+0x24554) (BuildId: 4232bf1566260aa8e8df3c044a913cc0946ea6d8)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/rafal/test/thorvg/build/../src/bin/svg2png/lodepng.cpp:391:10 in lodepng_save_file(unsigned char const*, unsigned long, char const*)
Uninitialized bytes in MemcmpInterceptorCommon at offset 40 inside [0x7ffe36c8b3c0, 256)
==585790==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x563fd221a6ed in __interceptor_memcmp (/home/rafal/test/thorvg/build/src/bin/svg2png/svg2png+0x5c6ed) (BuildId: 4232bf1566260aa8e8df3c044a913cc0946ea6d8)
    #1 0x7f14fc2e0ed1 in std::ctype<char>::_M_widen_init() const /build/gcc-13-oz92yP/gcc-13-13-20230320/build/x86_64-linux-gnu/libstdc++-v3/src/c++11/../../../../../src/libstdc++-v3/src/c++11/ctype.cc:98:25
    #2 0x7f14fc348b6f in std::ctype<char>::widen(char) const /build/gcc-13-oz92yP/gcc-13-13-20230320/build/x86_64-linux-gnu/libstdc++-v3/include/bits/locale_facets.h:884:21
    #3 0x7f14fc348b6f in std::ctype<char>::widen(char) const /build/gcc-13-oz92yP/gcc-13-13-20230320/build/x86_64-linux-gnu/libstdc++-v3/include/bits/locale_facets.h:880:7
    #4 0x7f14fc348b6f in std::basic_ios<char, std::char_traits<char>>::widen(char) const /build/gcc-13-oz92yP/gcc-13-13-20230320/build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_ios.h:450:45
    #5 0x7f14fc348b6f in std::basic_ostream<char, std::char_traits<char>>& std::endl<char, std::char_traits<char>>(std::basic_ostream<char, std::char_traits<char>>&) /build/gcc-13-oz92yP/gcc-13-13-20230320/build/x86_64-linux-gnu/libstdc++-v3/include/ostream:736:39
    #6 0x563fd226d5d8 in std::ostream::operator<<(std::ostream& (*)(std::ostream&)) /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/ostream:113:9
    #7 0x563fd226d5d8 in Renderer::render(char const*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned int) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:152:47
    #8 0x563fd226c415 in App::renderFile(char const*) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:342:25
    #9 0x563fd226b6ee in App::setup(int, char**) /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:264:36
    #10 0x563fd226ae35 in main /home/rafal/test/thorvg/build/../src/bin/svg2png/svg2png.cpp:413:16
    #11 0x7f14fbe23a8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #12 0x7f14fbe23b48 in __libc_start_main csu/../csu/libc-start.c:360:3
    #13 0x563fd21e2554 in _start (/home/rafal/test/thorvg/build/src/bin/svg2png/svg2png+0x24554) (BuildId: 4232bf1566260aa8e8df3c044a913cc0946ea6d8)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/rafal/test/thorvg/build/src/bin/svg2png/svg2png+0x5c6ed) (BuildId: 4232bf1566260aa8e8df3c044a913cc0946ea6d8) in __interceptor_memcmp
Generated PNG file: /home/rafal/Desktop/Untitled Folder/AA_5.png

```

**Comment by hermet** [comment]
This looks false-positive detection.
