### ISSUE TITLE
Memory problems that occur when the wasm class is destroyed

### ISSUE THREAD

**Issue by MrZillaGold** [thorvg/thorvg#2013]
When the emscripten class over wasm is no longer needed, you need to call the `delete` method as recommended in the documentation to free up occupied memory and prevent memory leaks.

https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#memory-management

Memory errors often occur when calling the `delete` method, here are a few error stacks:

```
RuntimeError: memory access out of bounds
    at thorvg-wasm.wasm.tvg::Scene::Impl::clear(bool) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[619]:0x199d5)
    at thorvg-wasm.wasm.tvg::Scene::clear(bool) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[618]:0x1992e)
    at thorvg-wasm.wasm.LottieBuilder::update(LottieComposition*, float) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[1785]:0x65dfb)
    at thorvg-wasm.wasm.LottieLoader::run(unsigned int) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[1933]:0x6ec0f)
    at thorvg-wasm.wasm.non-virtual thunk to LottieLoader::run(unsigned int) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[1952]:0x6f56e)
    at thorvg-wasm.wasm.tvg::TaskSchedulerImpl::request(tvg::Task*) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[728]:0x1d348)
    at thorvg-wasm.wasm.tvg::TaskScheduler::request(tvg::Task*) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[727]:0x1d2e4)
    at thorvg-wasm.wasm.LottieLoader::frame(float) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[1970]:0x704f6)
    at thorvg-wasm.wasm.tvg::Animation::frame(float) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[135]:0x8d50)
    at thorvg-wasm.wasm.TvgLottieAnimation::frame(float) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[3197]:0xcce0e)
```

```
RuntimeError: null function or function signature mismatch
    at thorvg-wasm.wasm.tvg::Picture::Impl::~Impl() (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[554]:0x17918)
    at thorvg-wasm.wasm.tvg::Picture::~Picture() (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[125]:0x899f)
    at thorvg-wasm.wasm.tvg::Picture::~Picture().1 (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[553]:0x17851)
    at thorvg-wasm.wasm.tvg::Canvas::Impl::clearPaints() (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[194]:0xae82)
    at thorvg-wasm.wasm.tvg::Canvas::Impl::~Impl() (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[251]:0xc116)
    at thorvg-wasm.wasm.tvg::Canvas::~Canvas().1 (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[161]:0x967f)
    at thorvg-wasm.wasm.tvg::SwCanvas::~SwCanvas().1 (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[711]:0x1cb5d)
    at thorvg-wasm.wasm.std::__2::default_delete<tvg::SwCanvas>::operator()[abi:un170004](tvg::SwCanvas*) const (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[3154]:0xcb598)
    at thorvg-wasm.wasm.std::__2::unique_ptr<tvg::SwCanvas, std::__2::default_delete<tvg::SwCanvas>>::reset[abi:un170004](tvg::SwCanvas*) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[3151]:0xcb48a)
    at thorvg-wasm.wasm.std::__2::unique_ptr<tvg::SwCanvas, std::__2::default_delete<tvg::SwCanvas>>::~unique_ptr[abi:un170004]() (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[3149]:0xcb3a4) 
```

```
RuntimeError: Aborted(native code called abort())
    at abort (https://manager_index_worker_js.js:489:51)
    at _abort (https://ex_worker_js.js:5475:13)
    at thorvg-wasm.wasm.dlfree (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[59]:0x4a5b)
    at thorvg-wasm.wasm.operator delete(void*) (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[126]:0x89d4)
    at thorvg-wasm.wasm.tvg::SwRenderer::~SwRenderer() (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[985]:0x3575d)
    at thorvg-wasm.wasm.tvg::SwRenderer::~SwRenderer().1 (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[995]:0x35b23)
    at thorvg-wasm.wasm.tvg::Canvas::Impl::~Impl() (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[251]:0xc14e)
    at thorvg-wasm.wasm.tvg::Canvas::~Canvas().1 (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[161]:0x967f)
    at thorvg-wasm.wasm.tvg::SwCanvas::~SwCanvas().1 (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[711]:0x1cb5d)
    at thorvg-wasm.wasm.std::__2::default_delete<tvg::SwCanvas>::operator()[abi:un170004](tvg::SwCanvas*) const (wasm://wasm/thorvg-wasm.wasm-013439fa:wasm-function[3154]:0xcb598)
```

The order of calling methods in JS:
```js
const thorvg = new TvgLottieAnimation();

thorvg.load();
thorvg.totalFrame();
thorvg.resize();
thorvg.frame();
thorvg.update();
thorvg.render();
thorvg.delete();
```

For each new lottie animation, a new instance of the `TvgLottieAnimation` class is created, after all animation frames have been rendered, the class is deleted using the `delete` method:

```js
const createAnimation = () => {
   const thorvg = new TvgLottieAnimation();
   
   thorvg.load();
   ...

   return () => thorvg.delete(); // destroy
};

createAnimation();
createAnimation();
...
```

**Comment by tinyjin** [comment]
Hello, @MrZillaGold.

Thanks for sharing the memory management.
We'll consider the explicit delete in official js player as emscripten strongly recommends it.

However I tried to call `thorvg.delete()` in our JS side, seemed to delete well, and there was no any runtime error.


![Screenshot 2024-03-07 at 10 43 13 PM](https://github.com/thorvg/thorvg/assets/11167117/1a58977a-35da-4014-8807-b526a00d78c0)
![Screenshot 2024-03-07 at 10 42 44 PM](https://github.com/thorvg/thorvg/assets/11167117/7003f621-4b03-470f-94d3-fe78b47d1456)

So I wonder which code base you tried specifically. If it's logical error in your js binding side, you can review our js [code](https://github.com/thorvg/thorvg/blob/main/web/src/lottie-player.ts) with `delete()`.

**Comment by MrZillaGold** [comment]
The problem occurs after several consecutive calls to emscripten methods, as I described above. The problem occurs randomly, I guess it depends on the number of calls to methods in total.

I use my own player, not the version from thorvg.

**Comment by MrZillaGold** [comment]
@tinyjin hey! 

https://github.com/MrZillaGold/thorvg-bug

I have created a minimal example with a reproduction of the problem, to run it you need to run:

- yarn
- yarn dev

after opening the browser tab on http://localhost:3000/ after 3-4 seconds, the players start drawing empty frames, at which point errors appear in the console and the CPU load on the browser tab increases to 100%.

<img width="371" alt="Снимок экрана 2024-03-25 в 10 24 56" src="https://github.com/thorvg/thorvg/assets/42776347/4294434b-bd11-4b0c-a859-7eff5ab25c54">

https://github.com/thorvg/thorvg/assets/42776347/94a7d1d8-2eea-4a1b-b90e-08bb2e070dd4

**Comment by tinyjin** [comment]
Hello, @MrZillaGold 
We also found that bug from calling ThorVG binding function after wasm has been deleted.
Will check the example and CPU load as well soon.

Thank you.

**Comment by tinyjin** [comment]
I've found memory leak between deletion and creation of `TvgLottieAnimation`.
It leaks `96bytes` in total for each recreation with given example, despite program called destructor and delete() function.

The `out of bounds` is also caused because the stack is going to be full. (Also that's the why it caused randomly)
The error could be delayed if we give Emscripten a parameter like `-sSTACK_SIZE=10MB`, but this isn't valid way to solve it.

Still unidentified issue, I'm not sure which part is exactly the point, will take a look into them.

<img width="970" alt="Screenshot 2024-03-27 at 2 50 43 PM" src="https://github.com/thorvg/thorvg/assets/11167117/660ed503-c926-465d-b59f-5748b5b5da62">

```text
SUMMARY: AddressSanitizer: 96 byte(s) leaked in 12 allocation(s).
```

**Comment by hermet** [comment]
@tinyjin I think you can firstly identify the constructor/destructor pair calls for TvgLottieAnimation / Animation and SwCanvas by placing a TVG log message in each of them.

**Comment by tinyjin** [comment]
The memory leak I found seems to come from EMSCRIPTEN_BINDING.
I've tested an example with empty function bindings.
```cpp
#include <emscripten/bind.h>
#include <sanitizer/lsan_interface.h>

using namespace emscripten;
using namespace std;

static const char* NoError = "None";

class __attribute__((visibility("default"))) TvgLottieAnimation
{
public:
    ~TvgLottieAnimation()
    {
    }

    static unique_ptr<TvgLottieAnimation> create()
    {
        return unique_ptr<TvgLottieAnimation>(new TvgLottieAnimation());
    }

    void render()
    {
    }

    bool update()
    {
        return true;
    }

    bool frame(float no)
    {
        return true;
    }

    void resize(int width, int height)
    {
    }

    TvgLottieAnimation()
    {
    }
};

EMSCRIPTEN_BINDINGS(thorvg_bindings)
{
    class_<TvgLottieAnimation>("TvgLottieAnimation")
        .constructor(&TvgLottieAnimation ::create) // No leak
        .function("render", &TvgLottieAnimation::render) // Leak 8 byte
        .function("update", &TvgLottieAnimation ::update) // Leak 8 byte
        .function("frame", &TvgLottieAnimation ::frame) // Leak 8 byte
        .function("resize", &TvgLottieAnimation ::resize); // Leak 8 byte

    emscripten::function("doLeakCheck", &__lsan_do_recoverable_leak_check); // No leak
}
```

In JS, I create the module and delete immediately.
```js
const tvg = new thorvg.TvgLottieAnimation();
tvg.delete();

// Check leak
thorvg.doLeakCheck();
```

![Screenshot 2024-04-05 at 1 17 26 PM](https://github.com/thorvg/thorvg/assets/11167117/b8940032-ca47-41cd-b241-8cf58416468b)

Although I didn't import any thorvg API and I just create them and delete, the sanitizer detects memory leak.
The binding seems to have 8 bytes leak per each class function.
I assume those leakings are from emscripten class function binding in unknown reason.

I'm going to take a look at similar issue on emscripten side and find workaround for this.

**Comment by tinyjin** [comment]
I've noticed that those leaks are not actual memory issue.
Although this somehow indicates a direct leak, it seems not to affect the WASM memory area.
see: https://github.com/emscripten-core/emscripten/issues/21709#issuecomment-2056799457

In addition, I've luckily found that v0.13.0 doesn't have same issue at all.
According to the my looking, the https://github.com/thorvg/thorvg/commit/efc7199e514cb40bfb1cff489b3043d363646738 eliminates the memory increment in calling `delete()`.

Hence, I want to check `v0.13.0` by your side as well. @MrZillaGold 
Could you please give them a try and check whether it still happens?

**Comment by MrZillaGold** [comment]
The problems in the test example that was attached above stopped being reproduced using the wasm build from the master branch. It seems the problem has been solved. We will additionally check the new version in the production environment, I will return with information later. Thanks!

**Comment by tinyjin** [comment]
Appreciate for that. I'll be still investigating for:
- How the commit eventually stops this issue.
- Way to avoid the fake memory leaks in Meson.

Once you can test, we can close this issue.
For sure, take your time on testing and let me know :)

**Comment by MrZillaGold** [comment]
@tinyjin 
We have tested the new version in the production environment and everything works without problems, thanks again!
