### ISSUE TITLE
gl_engine: memory leaks

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2461]
**Build Configure**
`meson setup builddir -Db_sanitize="address, undefined" -Dloaders=all -Dengines=all`

**ClipPath, Lottie, PictureRaw, SVG**
```
Direct leak of 1440 byte(s) in 18 object(s) allocated from:
    #0 0x7f0a70c531e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f0a700575b5 in GlRenderer::drawClip(tvg::Array<void*>&) ../src/renderer/gl_engine/tvgGlRenderer.cpp:844
    #2 0x7f0a70059e83 in GlRenderer::renderShape(void*) ../src/renderer/gl_engine/tvgGlRenderer.cpp:294
    #3 0x7f0a6ffa7152 in tvg::Shape::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgShape.h:60
    #4 0x7f0a6ff9e8e4 in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #5 0x7f0a6ffac18e in tvg::Scene::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgScene.h:139
    #6 0x7f0a6ff9eaab in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #7 0x7f0a6ffac18e in tvg::Scene::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgScene.h:139
    #8 0x7f0a6ff9eaab in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #9 0x7f0a6ffac18e in tvg::Scene::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgScene.h:139
    #10 0x7f0a6ff9eaab in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #11 0x7f0a6ffb288b in tvg::Picture::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPicture.cpp:83
    #12 0x7f0a6ff9ec72 in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #13 0x7f0a6ff87d0c in tvg::Canvas::Impl::draw() (/home/hermet/thorvg/build/examples/../src/libthorvg.so.0+0x6ecd0c)
    #14 0x7f0a6ff85a12 in tvg::Canvas::draw() ../src/renderer/tvgCanvas.cpp:67
    #15 0x557b181c086b in tvgexam::Window::draw() ../examples/Example.h:185
    #16 0x557b181c086b in tvgexam::Window::show() ../examples/Example.h:243
    #17 0x557b181bdd8c in tvgexam::main(tvgexam::Example*, int, char**, unsigned int, unsigned int, bool) ../examples/Example.h:533
    #18 0x7f0a6ec78d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 1440 byte(s) in 18 object(s) allocated from:
    #0 0x7f0a70c531e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f0a700583fc in GlRenderer::drawClip(tvg::Array<void*>&) ../src/renderer/gl_engine/tvgGlRenderer.cpp:864
    #2 0x7f0a70059e83 in GlRenderer::renderShape(void*) ../src/renderer/gl_engine/tvgGlRenderer.cpp:294
    #3 0x7f0a6ffa7152 in tvg::Shape::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgShape.h:60
    #4 0x7f0a6ff9e8e4 in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #5 0x7f0a6ffac18e in tvg::Scene::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgScene.h:139
    #6 0x7f0a6ff9eaab in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #7 0x7f0a6ffac18e in tvg::Scene::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgScene.h:139
    #8 0x7f0a6ff9eaab in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #9 0x7f0a6ffac18e in tvg::Scene::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgScene.h:139
    #10 0x7f0a6ff9eaab in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #11 0x7f0a6ffb288b in tvg::Picture::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPicture.cpp:83
    #12 0x7f0a6ff9ec72 in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #13 0x7f0a6ff87d0c in tvg::Canvas::Impl::draw() (/home/hermet/thorvg/build/examples/../src/libthorvg.so.0+0x6ecd0c)
    #14 0x7f0a6ff85a12 in tvg::Canvas::draw() ../src/renderer/tvgCanvas.cpp:67
    #15 0x557b181c086b in tvgexam::Window::draw() ../examples/Example.h:185
    #16 0x557b181c086b in tvgexam::Window::show() ../examples/Example.h:243
    #17 0x557b181bdd8c in tvgexam::main(tvgexam::Example*, int, char**, unsigned int, unsigned int, bool) ../examples/Example.h:533
    #18 0x7f0a6ec78d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
```

**AnimateMasking, Duplicate, InvLumaMasking, InvMasking, LumaMasking, Masking**
```
Direct leak of 27520 byte(s) in 344 object(s) allocated from:
    #0 0x7f82fdc581e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f82fd053f6a in GlRenderer::drawPrimitive(GlShape&, unsigned char, unsigned char, unsigned char, unsigned char, tvg::RenderUpdateFlag, int) ../src/renderer/gl_engine/tvgGlRenderer.cpp:567
    #2 0x7f82fd05f3e9 in GlRenderer::renderShape(void*) ../src/renderer/gl_engine/tvgGlRenderer.cpp:307
    #3 0x7f82fcfac172 in tvg::Shape::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgShape.h:60
    #4 0x7f82fcfa3904 in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #5 0x7f82fcfb11ae in tvg::Scene::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgScene.h:139
    #6 0x7f82fcfa3acb in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #7 0x7f82fcfb11ae in tvg::Scene::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgScene.h:139
    #8 0x7f82fcfa3acb in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #9 0x7f82fcfb11ae in tvg::Scene::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgScene.h:139
    #10 0x7f82fcfa3acb in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #11 0x7f82fcfb78ab in tvg::Picture::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPicture.cpp:83
    #12 0x7f82fcfa3c92 in tvg::Paint::Impl::render(tvg::RenderMethod*) ../src/renderer/tvgPaint.cpp:250
    #13 0x7f82fcf8cd2c in tvg::Canvas::Impl::draw() (/home/hermet/thorvg/build/examples/../src/libthorvg.so.0+0x6edd2c)
    #14 0x7f82fcf8aa32 in tvg::Canvas::draw() ../src/renderer/tvgCanvas.cpp:67
    #15 0x55557e899c0d in tvgexam::Window::draw() ../examples/Example.h:185
    #16 0x55557e899c0d in tvgexam::Window::show() ../examples/Example.h:243
    #17 0x55557e896c0c in tvgexam::main(tvgexam::Example*, int, char**, unsigned int, unsigned int, bool) ../examples/Example.h:533
    #18 0x7f82fbc7cd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
```

**Comment by hermet** [comment]
@RuiwenTang Hello, I believe you can fix those memory leak easily, please let me know if you can help this.
