### ISSUE TITLE
wg_engine: memory leak?

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2808]
Need to clarify the memory leaks report.

Test 'Shape' webgpu with this build:
```
meson setup build -Dexamples=true -Dloaders=all -Db_sanitize="address,undefined" -Dengines="wg_beta"
```

```
Direct leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x7f687ee39887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f687c15b5ac in wgpuSurfaceGetCurrentTexture (/usr/local/lib/libwgpu_native.so+0x1025ac)
    #2 0x7f687d4e137a in tvg::Canvas::Impl::sync() ../src/renderer/tvgCanvas.h:129
    #3 0x7f687d4e137a in tvg::Canvas::sync() ../src/renderer/tvgCanvas.cpp:86
    #4 0x5633152527bf in tvgexam::Window::ready() ../examples/Example.h:187
    #5 0x563315243506 in tvgexam::main(tvgexam::Example*, int, char**, unsigned int, unsigned int, unsigned int, bool) ../examples/Example.h:533
    #6 0x563315246a67 in main ../examples/Shape.cpp:56
    #7 0x7f687b5d6d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f687ee39887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f687c14cf2b in wgpuDeviceCreateBindGroupLayout (/usr/local/lib/libwgpu_native.so+0xf3f2b)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f687ee39887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f687c156096 in wgpuDeviceGetQueue (/usr/local/lib/libwgpu_native.so+0xfd096)
    #2 0x7f687d8a669a in WgRenderer::target(WGPUInstanceImpl*, WGPUSurfaceImpl*, unsigned int, unsigned int, WGPUDeviceImpl*) ../src/renderer/wg_engine/tvgWgRenderer.cpp:299
    #3 0x7f687d588b19 in tvg::WgCanvas::target(void*, void*, unsigned int, unsigned int, void*) ../src/renderer/tvgWgCanvas.cpp:73
    #4 0x563315259063 in tvgexam::WgWindow::resize() ../examples/Example.h:446
    #5 0x563315259063 in tvgexam::WgWindow::WgWindow(tvgexam::Example*, unsigned int, unsigned int, unsigned int) ../examples/Example.h:433
    #6 0x563315243209 in tvgexam::main(tvgexam::Example*, int, char**, unsigned int, unsigned int, unsigned int, bool) ../examples/Example.h:528
    #7 0x563315246a67 in main ../examples/Shape.cpp:56
    #8 0x7f687b5d6d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7f687ee3b1e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f687d588777 in tvg::WgCanvas::WgCanvas() ../src/renderer/tvgWgCanvas.cpp:43
    #2 0x7f687d5897b3 in tvg::WgCanvas::gen() ../src/renderer/tvgWgCanvas.cpp:89
    #3 0x563315258624 in tvgexam::WgWindow::WgWindow(tvgexam::Example*, unsigned int, unsigned int, unsigned int) ../examples/Example.h:425
    #4 0x563315243209 in tvgexam::main(tvgexam::Example*, int, char**, unsigned int, unsigned int, unsigned int, bool) ../examples/Example.h:528
    #5 0x563315246a67 in main ../examples/Shape.cpp:56
    #6 0x7f687b5d6d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
```

**Comment by SergeyLebedkin** [comment]
Seems to all there is not a problem of ThorVG WebGPU renderer.
Just double check in the standalone simple application with SDL2+WebGPU configuration.

We have same mem leaks messages that related to surface, bindg roups and instance:

```
Direct leak of 227480 byte(s) in 2585 object(s) allocated from:
    #0 0x7f814d857b37 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f814d2295ac in wgpuSurfaceGetCurrentTexture (/usr/local/lib/libwgpu_native.so+0x1025ac) (BuildId: 58b0b1d195679188b7050149b69ce5c85fef86b1)
    #2 0x55fb76708631 in __invoke_impl<void, main(int, char**)::<lambda()>&> /usr/include/c++/13/bits/invoke.h:61
    #3 0x55fb767084d1 in __invoke_r<void, main(int, char**)::<lambda()>&> /usr/include/c++/13/bits/invoke.h:150
    #4 0x55fb76708260 in _M_invoke /usr/include/c++/13/bits/std_function.h:290
    #5 0x55fb767089a9 in std::function<void ()>::operator()() const /usr/include/c++/13/bits/std_function.h:591
    #6 0x55fb76706eec in mainLoop(std::function<void ()>) ../src/main.cpp:106
    #7 0x55fb76707e6d in main ../src/main.cpp:166
    #8 0x7f814cab71c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #9 0x7f814cab728a in __libc_start_main_impl ../csu/libc-start.c:360
    #10 0x55fb76705ae4 in _start (/home/sliebodkin/projects/local/webgpu-sdl2-app/builddir/webgpu-cpp-app+0x4ae4) (BuildId: d231b43a71572b3e90b4dec65b71c35da5d66b0d)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x7f814d857b37 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f814d224cfa in wgpuInstanceCreateSurface (/usr/local/lib/libwgpu_native.so+0xfdcfa) (BuildId: 58b0b1d195679188b7050149b69ce5c85fef86b1)
    #2 0x55fb767079e6 in main ../src/main.cpp:126
    #3 0x7f814cab71c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #4 0x7f814cab728a in __libc_start_main_impl ../csu/libc-start.c:360
    #5 0x55fb76705ae4 in _start (/home/sliebodkin/projects/local/webgpu-sdl2-app/builddir/webgpu-cpp-app+0x4ae4) (BuildId: d231b43a71572b3e90b4dec65b71c35da5d66b0d)

```
