### ISSUE TITLE
lottie: image overrding memory leak

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#2959]
this must be addressed properly.

```
==23887==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 296 byte(s) in 1 object(s) allocated from:
    #0 0x7feec44351e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7feec31d3d49 in tvg::SwRenderer::prepare(tvg::RenderSurface*, void*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag) ../src/renderer/sw_engine/tvgSwRenderer.cpp:738
    #2 0x7feec30dcbf0 in tvg::Picture::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPicture.h:104
    #3 0x7feec30dcbf0 in tvg::Paint::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPaint.cpp:300
    #4 0x7feec30db838 in tvg::Scene::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgScene.h:118
    #5 0x7feec30db838 in tvg::Paint::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPaint.cpp:300
    #6 0x7feec30db838 in tvg::Scene::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgScene.h:118
    #7 0x7feec30db838 in tvg::Paint::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPaint.cpp:300
    #8 0x7feec30de745 in tvg::Picture::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPicture.h:111
    #9 0x7feec30de745 in tvg::Paint::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPaint.cpp:300
    #10 0x7feec309f4f2 in tvg::Canvas::Impl::update(tvg::Paint*, bool) ../src/renderer/tvgCanvas.h:98
    #11 0x7feec309f4f2 in tvg::Canvas::Impl::push(tvg::Paint*) ../src/renderer/tvgCanvas.h:70
    #12 0x7feec309f4f2 in tvg::Canvas::push(tvg::Paint*) ../src/renderer/tvgCanvas.cpp:48
    #13 0x55db93326fda in UserExample::content(tvg::Canvas*, unsigned int, unsigned int) ../examples/LottieExtension.cpp:163
    #14 0x55db9332c65f in tvgexam::Window::ready() ../examples/Example.h:185
    #15 0x55db9331250f in tvgexam::main(tvgexam::Example*, int, char**, unsigned int, unsigned int, unsigned int, bool) ../examples/Example.h:522
    #16 0x55db93316d2e in main ../examples/LottieExtension.cpp:189
    #17 0x7feec1ac2d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7feec44351e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7feec30cc90b in tvg::Paint::Paint() ../src/renderer/tvgPaint.cpp:387
    #2 0x7feec30ef271 in tvg::Picture::Picture() ../src/renderer/tvgPicture.cpp:134
    #3 0x7feec30ef7ab in tvg::Picture::gen() ../src/renderer/tvgPicture.cpp:147
    #4 0x7feec35ec439 in LottieImage::prepare() ../src/loaders/lottie/tvgLottieModel.cpp:175
    #5 0x7feec36fa285 in LottieParser::parseAsset() ../src/loaders/lottie/tvgLottieParser.cpp:992
    #6 0x7feec36faefd in LottieParser::parseAssets() ../src/loaders/lottie/tvgLottieParser.cpp:1023
    #7 0x7feec37008aa in LottieParser::parse() ../src/loaders/lottie/tvgLottieParser.cpp:1592
    #8 0x7feec35d54b9 in non-virtual thunk to LottieLoader::run(unsigned int) (/home/hermet/Projects/thorvg/build/examples/../src/libthorvg.so.1+0xef04b9)
    #9 0x7feec312a8df in tvg::Task::operator()(unsigned int) ../src/renderer/tvgTaskScheduler.h:64
    #10 0x7feec312a8df in tvg::TaskSchedulerImpl::run(unsigned int) ../src/renderer/tvgTaskScheduler.cpp:153
    #11 0x7feec312a8df in tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}::operator()() const ../src/renderer/tvgTaskScheduler.cpp:120
    #12 0x7feec312a8df in void std::__invoke_impl<void, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_other, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/invoke.h:61
    #13 0x7feec312a8df in std::__invoke_result<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>::type std::__invoke<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/invoke.h:96
    #14 0x7feec312a8df in void std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/11/bits/std_thread.h:259
    #15 0x7feec312a8df in std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::operator()() /usr/include/c++/11/bits/std_thread.h:266
    #16 0x7feec312a8df in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> > >::_M_run() /usr/include/c++/11/bits/std_thread.h:211
    #17 0x7feec23f5252  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc252)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7feec44351e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7feec31d6b2f in tvg::SwRenderer::gen() ../src/renderer/sw_engine/tvgSwRenderer.cpp:807
    #2 0x7feec312268d in tvg::SwCanvas::SwCanvas() ../src/renderer/tvgSwCanvas.cpp:49
    #3 0x7feec3123bb7 in tvg::SwCanvas::gen() ../src/renderer/tvgSwCanvas.cpp:116
    #4 0x55db93311c8f in tvgexam::SwWindow::SwWindow(tvgexam::Example*, unsigned int, unsigned int, unsigned int) ../examples/Example.h:281
    #5 0x55db93311c8f in tvgexam::main(tvgexam::Example*, int, char**, unsigned int, unsigned int, unsigned int, bool) ../examples/Example.h:513
    #6 0x55db93316d2e in main ../examples/LottieExtension.cpp:189
    #7 0x7feec1ac2d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7feec44351e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7feec31c9125 in tvg::SwRenderer::target(unsigned int*, unsigned int, unsigned int, unsigned int, tvg::ColorSpace) ../src/renderer/sw_engine/tvgSwRenderer.cpp:358
    #2 0x7feec3122eb8 in tvg::SwCanvas::target(unsigned int*, unsigned int, unsigned int, unsigned int, tvg::ColorSpace) ../src/renderer/tvgSwCanvas.cpp:96
    #3 0x55db93312199 in tvgexam::SwWindow::resize() ../examples/Example.h:296
    #4 0x55db93312199 in tvgexam::SwWindow::SwWindow(tvgexam::Example*, unsigned int, unsigned int, unsigned int) ../examples/Example.h:287
    #5 0x55db93312199 in tvgexam::main(tvgexam::Example*, int, char**, unsigned int, unsigned int, unsigned int, bool) ../examples/Example.h:513
    #6 0x55db93316d2e in main ../examples/LottieExtension.cpp:189
    #7 0x7feec1ac2d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x7feec4433c38 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:164
    #1 0x7feec31d25d5 in tvg::Array<SwTask*>::push(SwTask*) ../src/common/tvgArray.h:57
    #2 0x7feec31d25d5 in tvg::SwRenderer::prepareCommon(SwTask*, tvg::Matrix const&, tvg::Array<void*> const&, unsigned char, tvg::RenderUpdateFlag) ../src/renderer/sw_engine/tvgSwRenderer.cpp:725
    #3 0x7feec31d39c3 in tvg::SwRenderer::prepare(tvg::RenderSurface*, void*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag) ../src/renderer/sw_engine/tvgSwRenderer.cpp:743
    #4 0x7feec30dcbf0 in tvg::Picture::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPicture.h:104
    #5 0x7feec30dcbf0 in tvg::Paint::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPaint.cpp:300
    #6 0x7feec30db838 in tvg::Scene::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgScene.h:118
    #7 0x7feec30db838 in tvg::Paint::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPaint.cpp:300
    #8 0x7feec30db838 in tvg::Scene::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgScene.h:118
    #9 0x7feec30db838 in tvg::Paint::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPaint.cpp:300
    #10 0x7feec30de745 in tvg::Picture::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPicture.h:111
    #11 0x7feec30de745 in tvg::Paint::Impl::update(tvg::RenderMethod*, tvg::Matrix const&, tvg::Array<void*>&, unsigned char, tvg::RenderUpdateFlag, bool) ../src/renderer/tvgPaint.cpp:300
    #12 0x7feec309f4f2 in tvg::Canvas::Impl::update(tvg::Paint*, bool) ../src/renderer/tvgCanvas.h:98
    #13 0x7feec309f4f2 in tvg::Canvas::Impl::push(tvg::Paint*) ../src/renderer/tvgCanvas.h:70
    #14 0x7feec309f4f2 in tvg::Canvas::push(tvg::Paint*) ../src/renderer/tvgCanvas.cpp:48
    #15 0x55db93326fda in UserExample::content(tvg::Canvas*, unsigned int, unsigned int) ../examples/LottieExtension.cpp:163
    #16 0x55db9332c65f in tvgexam::Window::ready() ../examples/Example.h:185
    #17 0x55db9331250f in tvgexam::main(tvgexam::Example*, int, char**, unsigned int, unsigned int, unsigned int, bool) ../examples/Example.h:522
    #18 0x55db93316d2e in main ../examples/LottieExtension.cpp:189
    #19 0x7feec1ac2d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7feec44351e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7feec30ef2ae in tvg::Picture::Picture() ../src/renderer/tvgPicture.cpp:134
    #2 0x7feec30ef7ab in tvg::Picture::gen() ../src/renderer/tvgPicture.cpp:147
    #3 0x7feec35ec439 in LottieImage::prepare() ../src/loaders/lottie/tvgLottieModel.cpp:175
    #4 0x7feec36fa285 in LottieParser::parseAsset() ../src/loaders/lottie/tvgLottieParser.cpp:992
    #5 0x7feec36faefd in LottieParser::parseAssets() ../src/loaders/lottie/tvgLottieParser.cpp:1023
    #6 0x7feec37008aa in LottieParser::parse() ../src/loaders/lottie/tvgLottieParser.cpp:1592
    #7 0x7feec35d54b9 in non-virtual thunk to LottieLoader::run(unsigned int) (/home/hermet/Projects/thorvg/build/examples/../src/libthorvg.so.1+0xef04b9)
    #8 0x7feec312a8df in tvg::Task::operator()(unsigned int) ../src/renderer/tvgTaskScheduler.h:64
    #9 0x7feec312a8df in tvg::TaskSchedulerImpl::run(unsigned int) ../src/renderer/tvgTaskScheduler.cpp:153
    #10 0x7feec312a8df in tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}::operator()() const ../src/renderer/tvgTaskScheduler.cpp:120
    #11 0x7feec312a8df in void std::__invoke_impl<void, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_other, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/invoke.h:61
    #12 0x7feec312a8df in std::__invoke_result<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>::type std::__invoke<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/invoke.h:96
    #13 0x7feec312a8df in void std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/11/bits/std_thread.h:259
    #14 0x7feec312a8df in std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::operator()() /usr/include/c++/11/bits/std_thread.h:266
    #15 0x7feec312a8df in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> > >::_M_run() /usr/include/c++/11/bits/std_thread.h:211
    #16 0x7feec23f5252  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc252)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7feec44351e7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7feec30ef797 in tvg::Picture::gen() ../src/renderer/tvgPicture.cpp:147
    #2 0x7feec35ec439 in LottieImage::prepare() ../src/loaders/lottie/tvgLottieModel.cpp:175
    #3 0x7feec36fa285 in LottieParser::parseAsset() ../src/loaders/lottie/tvgLottieParser.cpp:992
    #4 0x7feec36faefd in LottieParser::parseAssets() ../src/loaders/lottie/tvgLottieParser.cpp:1023
    #5 0x7feec37008aa in LottieParser::parse() ../src/loaders/lottie/tvgLottieParser.cpp:1592
    #6 0x7feec35d54b9 in non-virtual thunk to LottieLoader::run(unsigned int) (/home/hermet/Projects/thorvg/build/examples/../src/libthorvg.so.1+0xef04b9)
    #7 0x7feec312a8df in tvg::Task::operator()(unsigned int) ../src/renderer/tvgTaskScheduler.h:64
    #8 0x7feec312a8df in tvg::TaskSchedulerImpl::run(unsigned int) ../src/renderer/tvgTaskScheduler.cpp:153
    #9 0x7feec312a8df in tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}::operator()() const ../src/renderer/tvgTaskScheduler.cpp:120
    #10 0x7feec312a8df in void std::__invoke_impl<void, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_other, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/invoke.h:61
    #11 0x7feec312a8df in std::__invoke_result<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>::type std::__invoke<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/invoke.h:96
    #12 0x7feec312a8df in void std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/11/bits/std_thread.h:259
    #13 0x7feec312a8df in std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::operator()() /usr/include/c++/11/bits/std_thread.h:266
    #14 0x7feec312a8df in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> > >::_M_run() /usr/include/c++/11/bits/std_thread.h:211
    #15 0x7feec23f5252  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc252)

SUMMARY: AddressSanitizer: 856 byte(s) leaked in 7 allocation(s).
```

_Originally posted by @hermet in https://github.com/thorvg/thorvg/pull/2935#discussion_r1843496201_

**Comment by hermet** [comment]
\+ @tinyjin
