### ISSUE TITLE
clippath doesn't work with scene

### ISSUE THREAD

**Issue by JSUYA** [thorvg/thorvg#524]
Segmentation fault occurs when scene is input as composite( with clippath) argument.

```
btThread 1 "Scene" received signal SIGSEGV, Segmentation fault.
tvg::Task::done (this=0x0) at ../src/lib/tvgTaskScheduler.h:55
55	        if (!pending) return;
(gdb) bt
#0  tvg::Task::done (this=0x0) at ../src/lib/tvgTaskScheduler.h:55
#1  0x00007ffff7bc264d in tvg::SwRenderer::prepareCommon (flags=tvg::All, clips=..., opacity=255, transform=0x0, task=0x555555dcb8a0, this=0x555555d85410)
    at ../src/lib/sw_engine/tvgSwRenderer.cpp:553
#2  tvg::SwRenderer::prepareCommon (this=0x555555d85410, task=0x555555dcb8a0, transform=0x0, opacity=255, clips=..., flags=tvg::All) at ../src/lib/sw_engine/tvgSwRenderer.cpp:542
#3  0x00007ffff7bbcad0 in tvg::Shape::Impl::update (pFlag=<optimized out>, clips=..., opacity=<optimized out>, transform=<optimized out>, renderer=..., this=0x555555d854f0)
    at ../src/lib/tvgShapeImpl.h:234
#4  tvg::PaintMethod<tvg::Shape::Impl>::update (this=<optimized out>, renderer=..., transform=<optimized out>, opacity=<optimized out>, clips=..., flag=<optimized out>)
    at ../src/lib/tvgPaint.h:142
#5  0x00007ffff7bba1ff in tvg::Paint::Impl::update (this=0x555555d854c0, renderer=..., pTransform=pTransform@entry=0x0, opacity=<optimized out>, opacity@entry=255, clips=..., 
    pFlag=pFlag@entry=127) at ../src/lib/tvgPaint.cpp:231
#6  0x00007ffff7bbb87c in tvg::Scene::Impl::update (flag=<optimized out>, clips=..., opacity=<optimized out>, transform=0x0, renderer=..., this=0x555555d841e0)
    at ../src/lib/tvgSceneImpl.h:75
#7  tvg::PaintMethod<tvg::Scene::Impl>::update (this=<optimized out>, renderer=..., transform=0x0, opacity=<optimized out>, clips=..., flag=<optimized out>)
    at ../src/lib/tvgPaint.h:142
#8  0x00007ffff7bba1ff in tvg::Paint::Impl::update (this=0x555555d838d0, renderer=..., pTransform=pTransform@entry=0x0, opacity=<optimized out>, opacity@entry=255, clips=..., 
    pFlag=<optimized out>) at ../src/lib/tvgPaint.cpp:231
#9  0x00007ffff7bb91db in tvg::Canvas::Impl::update (this=0x555555d83930, paint=<optimized out>, force=<optimized out>) at ../src/lib/tvgCanvasImpl.h:96
#10 0x00005555555565f3 in tvgDrawCmds (canvas=0x555555d84840) at /usr/include/c++/9/bits/move.h:74
#11 tvgDrawCmds (canvas=0x555555d84840) at ../src/examples/Scene.cpp:29
#12 0x00005555555566e8 in tvgSwTest (buffer=0x555555758180 <createSwView()::buffer>) at /usr/include/c++/9/bits/unique_ptr.h:360
#13 0x0000555555555edc in createSwView () at ../src/examples/Common.h:65
#14 main (argc=<optimized out>, argv=<optimized out>) at ../src/examples/Scene.cpp:192
(gdb) 

```

[Code]
This code has been modified in Scene.cpp.
```cpp
    //Create a Scene
    auto scene = tvg::Scene::gen();
    scene->reserve(3);   //reserve 3 shape nodes (optional)

    //Prepare Round Rectangle
    auto shape1 = tvg::Shape::gen();
    shape1->appendRect(0, 0, 400, 400, 50, 50);  //x, y, w, h, rx, ry
    shape1->fill(0, 255, 0, 255);                //r, g, b, a
    scene->push(move(shape1));

    //Prepare Circle
    auto shape2 = tvg::Shape::gen();
    shape2->appendCircle(400, 400, 200, 200);    //cx, cy, radiusW, radiusH
    shape2->fill(255, 255, 0, 255);              //r, g, b, a
    scene->push(move(shape2));

    //Prepare Ellipse
    auto shape3 = tvg::Shape::gen();
    shape3->appendCircle(600, 600, 150, 100);    //cx, cy, radiusW, radiusH
    shape3->fill(0, 255, 255, 255);              //r, g, b, a
    scene->push(move(shape3));

    //Create another Scene
    auto scene2 = tvg::Scene::gen();
    scene2->reserve(2);   //reserve 2 shape nodes (optional)

    //Star
    auto shape4 = tvg::Shape::gen();

    //Appends Paths
    shape4->moveTo(199, 34);
    shape4->lineTo(253, 143);
    shape4->lineTo(374, 160);
    shape4->lineTo(287, 244);
    shape4->lineTo(307, 365);
    shape4->lineTo(199, 309);
    shape4->lineTo(97, 365);
    shape4->lineTo(112, 245);
    shape4->lineTo(26, 161);
    shape4->lineTo(146, 143);
    shape4->close();
    shape4->fill(0, 0, 255, 255);
    scene2->push(move(shape4));

    //Circle
    auto shape5 = tvg::Shape::gen();

    auto cx = 550.0f;
    auto cy = 550.0f;
    auto radius = 125.0f;
    auto halfRadius = radius * 0.552284f;

    //Append Paths
    shape5->moveTo(cx, cy - radius);
    shape5->cubicTo(cx + halfRadius, cy - radius, cx + radius, cy - halfRadius, cx + radius, cy);
    shape5->cubicTo(cx + radius, cy + halfRadius, cx + halfRadius, cy + radius, cx, cy+ radius);
    shape5->cubicTo(cx - halfRadius, cy + radius, cx - radius, cy + halfRadius, cx - radius, cy);
    shape5->cubicTo(cx - radius, cy - halfRadius, cx - halfRadius, cy - radius, cx, cy - radius);
    shape5->fill(255, 0, 0, 255);
    scene2->push(move(shape5));

    //Push scene2 onto the scene
//   scene->push(move(scene2));
//    scene->composite(move(scene2), tvg::CompositeMethod::AlphaMask);
    scene->composite(move(scene2), tvg::CompositeMethod::ClipPath);


    //Draw the Scene onto the Canvas
    canvas->push(move(scene));

```

**Comment by hermet** [comment]
result:
![image](https://user-images.githubusercontent.com/3711518/232313420-ec1142d2-07e2-409e-b392-e0d3f0158b29.png)

**Comment by hermet** [comment]
the feature is broken by https://github.com/thorvg/thorvg/pull/1419
